import CaseStudyLayout from "@/components/CaseStudyLayout"

export default function FmeProject() {
  return (

    <CaseStudyLayout
      title="Reducing Clutter Without Losing Context"
      category="Product Design"
      year="2024"
      role="Product Design Intern"
      cover="/AnnotationVid.mp4"
      overview={""}
      specs={[
        { label: "Team",     value: "4 Members" },
        { label: "Duration", value: "April – August 2024" },
      ]}
      sections={[
        {
          label: "Context",
          title: "What is annotation in FME Form.",
          body: "During my internship at Safe Software, I led the end-to-end redesign of the annotation experience in FME Form, a data integration platform used to build complex spatial workflows. Annotations are notes users can place directly on the canvas to add context, explain decisions, or document logic within a workflow. They come in two forms:",
          contents: [
            {
              highlight: true,
              minimal:   true,
              title: "Custom Annotations.",
              body:  "Created manually by users, with full control over the content. Used to document logic, explain decisions, or add context.",
              images: ["/Custom.png"],
            },
            {
              highlight: true,
              minimal:   true,
              title: "Summary Annotations.",
              body:  "Auto-generated by the software. Contents are predefined and describe what an object does.",
              images: ["/Summary.png"],
            },
          ],
        },
        {
          label: "Problem Space",
          contents: [
            {
              title: "No visibility controls.",
              body:  "Annotations were essential for adding context, but as workflows grew larger they became a source of clutter. Users had no way to hide or collapse them, so the more documentation a workflow had, the harder it became to read.",
              image: "/NoVisibility.png",
            },
            {
              title: "And when they were visible, they still weren't enough.",
              body:  "Summary annotations describe what an object does, but not why it's configured a certain way. Users had to write their own custom annotations just to fill in the gaps, adding more to a canvas that was already overloaded.",
              videos: ["/NoContextAnnotation.mp4"],
            },
          ],
        },
        {
          label: "User Research",
          title: "What the FME Community told us.",
          body:  "We pulled feedback from the FME Community platform and conducted user interviews to understand the scope. A recurring theme emerged: users wanted annotations to be collapsible and available directly inside the parameter dialog, so context stays visible exactly where configuration decisions are made.",
          image: "/WhatUserSaid.png",
          contents: [
            {
              title: "The workaround told us everything.",
              body:  "We found users tucking annotations into bookmarks just to collapse and hide them. It kept things tidier but added friction and stripped away context. It was a clear signal: the need for visibility control was real, and users were paying a cost every time they worked around it.",
              videos: ["/WorkaroundAnnotation.mp4"],
            },
          ],
        },
        {
          label: "Project Direction",
          title: "Creating a more comprehensive annotation experience.",
          body:  "Following our research, the team identified two potential solutions.",
          contents: [
            {
              highlight: true,
              minimal:   true,
              icon:      "layers",
              title:     "Dynamic Visibility.",
              body:      "Let users toggle annotations between expanded and minimized states directly on the canvas.",
            },
            {
              highlight: true,
              minimal:   true,
              icon:      "zap",
              title:     "Annotation in Parameter Dialog.",
              body:      "Bring notes into the parameter editor, so context lives right where configuration decisions are made.",
            },
          ],
        },
        {
          label: "Audit",
          contents: [
            {
              title: "Where does a collapsed annotation live?",
              body:  "We mapped the current canvas object layout and found the right side of the object header was the only viable spot. The left was already reserved for alert and warning indicators.",
              image: "/Visibility Control Audit.png",
            },
            {
              title: "Where does an inline annotation fit?",
              body:  "For the parameter dialog, we placed the annotation option inside the existing dropdown area where users already define parameter logic. It fit naturally into a workflow they already understood.",
              image: "/AnnotationDialogAudit.png",
            },
          ],
        },
        {
          label: "Annotation Visibility",
          tocLabel: "Design Decisions",
          contents: [
            {
              title:  "Annotations can now be collapsed.",
              body:   "Users can minimize any annotation into an icon on the object header, keeping the canvas clean without losing access to the context.",
              videos: ["/HiddenAnnotation.mp4"],
            },
            {
              title: "A single place for all annotations.",
              body:  "I grouped all annotations under a single side panel, giving users a way to navigate between them quickly without having to hunt through the canvas. Each annotation is color coded to show whether it's custom or summary, and which object it's attached to.",
              videos: ["/AnnotationWindow.mp4"],
            },
          ],
        },
        {
          label: "Parameter Dialog",
          hideToc: true,
          contents: [
            {
              title:  "Context lives where decisions are made.",
              body:   "Users were constantly switching between the canvas and parameter dialogs to reference their notes. Bringing annotations directly into the dialog closed that loop entirely.",
              videos: ["/InLineAnnotation.mp4"],
            },
          ],
        },
        {
          label: "Stakeholder Review",
          hideToc: true,
          title: "Design evaluation and stakeholder feedback.",
          body:  "We used storyboarding to walk PMs and engineers through the proposed flow and interactions, gathering feedback and opportunities to improve before moving to higher fidelity.",
          image: "/storyboarding1.png",
        },
        {
          label: "Iteration",
          title: "Showing annotation on a different level.",
          body:  "Annotations inside the parameter dialog weren't getting enough visibility on their own. We explored surfacing them at both the group and canvas levels using icons and formatted text as indicators, and brought them into the navigator so users could locate annotations quickly without digging through the canvas.",
          images: ["/AnnotationCanvas.png", "/AnnotationNavigator.png"],
        },
        {
          label: "Usability Testing",
          title: "Putting the design in front of real users.",
          body:  "We ran qualitative usability tests with four customer success team members experienced in FME Workbench. Using detailed test plans and an interactive prototype, we gathered feedback on usability and functionality.\n\nParticipants completed 96% of the required tasks and indicated that the feature would provide meaningful value in their day-to-day workflows.",
          image: "/UsabilityTestingFME.png",
        },
        {
          label: "Shipping",
          title: "57% reduction in visible canvas clutter.",
          body:  "Post-launch, users navigated and read complex workflows more efficiently. For the first time, they could add context exactly where configuration decisions are made, without it spilling onto the canvas. The response from the community reflected that.",
          image: "/linkedInComments.png",
          footnote: "User reactions on LinkedIn following the release.",
        },
      ]}
    />


  )
}
